[package]
name = "sod2se-game-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
sod2se-abi.workspace = true
sod2se-services.workspace = true
serde.workspace = true
serde_json.workspace = true
[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
[build-dependencies]
cc = "1"

